project_name: demo_project
description: "Ce projet utilise Nginx et PostgreSQL pour démontrer un déploiement de conteneurs."


containers:
  - name: demo_web
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - demo_network

  - name: demo_db
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - demo_project_network

networks:
  - demo_project_network
