# Utilise une image légère de Node.js
FROM node:18-alpine

# Crée un dossier de travail dans le conteneur
WORKDIR /app

# Copie uniquement les fichiers package.json pour installer les dépendances
COPY package*.json ./

# Installe les dépendances dans le conteneur
RUN npm install dockerode cors express jsonwebtoken

# Copie le reste des fichiers de l'application
COPY . .

# Expose le port 4000 pour le service admin
EXPOSE 4000

# Lance le serveur
CMD ["node", "adminServer.mjs"]
